---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(anomalize)
library(tibbletime)
library(forecast)
library(lubridate)
library(patchwork)
library(tsibble)
library(feasts)
library(gsheet)

```

Note timestamp is in UTC timezone. 
```{r}
er_wait_times <- read_csv("waittimes_record.csv")

realtime_hospital_list <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1MCiyFx-kC2Et88taXHt49x4W0PTJboJ93A-SmZ9Ed4Q/edit?usp=sharing")

er_wait_times <- er_wait_times %>% 
  left_join(realtime_hospital_list, by = "site_labels")
```


```{r}
er_wait_time_scatter <- er_wait_times %>% 
  filter(!is.na(State)) %>% 
  ggplot(aes(x = read_timestamp, y = total_minutes)) + 
  facet_wrap(~ facility_type, ncol = 1) +
  geom_point(aes(color = State)) +
  theme_minimal() +
  geom_smooth() 

er_wait_time_scatter
```

```{r}
state_range <- er_wait_times %>% 
  filter(!is.na(State)) %>% 
  group_by(State) %>% 
  summarize(max_timestamp = max(read_timestamp),
            min_timestamp = min(read_timestamp))

ggplot(state_range, aes(x = fct_rev(State))) +
  geom_linerange(aes(ymin = min_timestamp, ymax = max_timestamp, color = State), size = 7) + 
  scale_y_datetime(limits = c(min(er_wait_times$read_timestamp), max(er_wait_times$read_timestamp))) +
  coord_flip() + 
  theme_minimal()
```


```{r}
facilities_recorded_plot <- er_wait_times %>% 
  filter(!is.na(State)) %>% 
  mutate(nearest_hour = round_date(read_timestamp, "hour")) %>% 
  group_by(nearest_hour) %>%
  summarize(obs = n_distinct(site_labels)) %>% 
  ggplot(aes(x = nearest_hour, y = obs)) + 
  geom_col() +
  theme_minimal()

facilities_recorded_plot
```

```{r}
er_wait_time_scatter / facilities_recorded_plot
```


```{r}

er_wait_times %>%
  filter(!is.na(State)) %>% 
  ggplot(aes(x = hospital_webpage, y = total_minutes)) +
  geom_boxplot() + 
  #stat_summary(fun.data = give.n, geom = "text", fun.y = median,
                  #position = position_dodge(width = 0.75)) +
  facet_wrap(~State, scales = "free_x") +
  theme_minimal() +
  ylab("Stated Wait Time (Minutes)") +
  xlab("")
```

```{r}
er_wait_times_ts <- er_wait_times %>% 
  select(read_timestamp, site_labels, total_minutes) %>%
  distinct(.keep_all = T) %>% 
  as_tsibble(key = site_labels, index = read_timestamp) %>% 
  fill_gaps()

gg_season(er_wait_times_ts, total_minutes)
```

